//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipMaintSys1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public string Serial_Num { get; set; }
        public string Name { get; set; }
        public string Supplier { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> Date_Replaced { get; set; }
        public string Linked_Equiptment { get; set; }
        public string Kept_In_Stock { get; set; }
        public string Archived { get; set; }
        public string Archived_By { get; set; }
    }
}
