//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipMaintSys1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public string Company_Name { get; set; }
        public string Contact_Name { get; set; }
        public string Phone_Num_1 { get; set; }
        public string Phone_Num_2 { get; set; }
        public string CompAddress { get; set; }
        public string Archived { get; set; }
        public string Archived_By { get; set; }
    }
}
