//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipMaintSys1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Name { get; set; }
        public string EmpNum { get; set; }
        public string UserPassword { get; set; }
        public string Dept { get; set; }
        public string Manager { get; set; }
        public string Emp_Type { get; set; }
        public string Archived { get; set; }
        public string Archived_By { get; set; }
    }
}
