//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipMaintSys1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class L00143846_EquiptMaintSys1Entities : DbContext
    {
        public L00143846_EquiptMaintSys1Entities()
            : base("name=L00143846_EquiptMaintSys1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Equiptment> Equiptments { get; set; }
        public virtual DbSet<Fault_Log> Fault_Log { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Maintenance_Schedule> Maintenance_Schedule { get; set; }
    }
}
