//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipMaintSys1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equiptment
    {
        public string Serial_Num { get; set; }
        public string Name { get; set; }
        public string Supplier { get; set; }
        public string Manufacturer { get; set; }
        public System.DateTime Date_of_Purchase { get; set; }
        public System.DateTime Warranty_Expire { get; set; }
        public string Support { get; set; }
        public string Downtime_cost_hr { get; set; }
        public string Archived { get; set; }
        public string Archived_By { get; set; }
    }
}
