//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipMaintSys1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fault_Log
    {
        public string Event_Num { get; set; }
        public string Equiptment { get; set; }
        public string Component { get; set; }
        public string Downtime { get; set; }
        public string Technician { get; set; }
        public string Fault_Description { get; set; }
        public System.DateTime Start_Date_Time { get; set; }
        public System.DateTime End_Date_Time { get; set; }
    }
}
