//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipMaintSys1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance_Schedule
    {
        public string Name { get; set; }
        public string Equiptment { get; set; }
        public string Downtime { get; set; }
        public string Implementor { get; set; }
        public string Job_Description { get; set; }
        public string Frequency { get; set; }
        public System.DateTime Start_Date_Time { get; set; }
        public System.DateTime End_Date_Time { get; set; }
        public string Archived { get; set; }
        public string Archived_by { get; set; }
    }
}
